trigger:
- main

resources:
- repo: self

variables:
  imagePullSecret: 'devopsmelacr132827a7-auth'

pool:
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    workspace:
      clean: all
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'SonarQube'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.qualitygate.wait=true
#    - task: SonarQubePublish@6
#      inputs:
#        pollingTimeoutSec: '300'
#    - task: sonar-buildbreaker@8
#      inputs:
#        SonarQube: 'SonarQube'
    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'Maven'
        mavenServiceConnections: 'Maven-ServiceConnection'
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'deploy sonar:sonar'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
- stage: DockerImageBuild
  displayName: DockerImageBuild
  dependsOn: Build
  jobs:
  - job: DockerImageBuild
    displayName: DockerImageBuild
    steps:
    - checkout: none
    - task: CmdLine@2
      inputs:
        script: |
          docker system prune -f --all
          docker build -t myimage:1.06 .
          docker tag myimage:1.06 akscontainer24registry.azurecr.io/samplewebapp:$(Build.BuildId)
          trivy image --exit-code 0 --severity MEDIUM,HIGH akscontainer24registry.azurecr.io/samplewebapp:$(Build.BuildId)
         #trivy image --exit-code 1 --severity CRITICAL akscontainer24registry.azurecr.io/samplewebapp:$(Build.BuildId)
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerRegistryServiceConnection'
        repository: 'samplewebapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
- stage: KubernetesDeployment
  displayName: KubernetesDeployment
  dependsOn: DockerImageBuild
  jobs:
  - deployment: KubernetesDeployment
    environment: "dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Azure DevOps Service Connection'
              azureResourceGroup: 'aks-rg'
              kubernetesCluster: 'aks-cluster'
              namespace: 'three-tier'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '/home/demo/folo'
              releaseName: 'threetierapp'
              overrideValues: 'imagePullSecrets[0].name=devopsmelacr132827a7-auth,image.repository=akscontainer24registry.azurecr.io/samplewebapp,image.tag=$(Build.BuildId),replicaCount=1,service.type=ClusterIP,service.port=80'
